name: build

on: [push, pull_request]

jobs:
  upload-src:
    name: upload source
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            bison cmake flex g++ gcc libexpat1-dev libfmt-dev \
            libgtest-dev libpng-dev libprotobuf-dev pkg-config \
            protobuf-compiler
      - name: checkout
        uses: actions/checkout@v7
        with:
          submodules: true
      - name: git config
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - name: build
        run: |
          export SOURCE_DATE_EPOCH=$(date +%s)
          echo "SOURCE_DATE_EPOCH: ${SOURCE_DATE_EPOCH}"
          cmake -B build
          tar -chzf android-build-tools.tar.gz -T tarball-files.txt --transform='s|^|android-build-tools/|'
          for x in sha1sum sha256sum sha512sum b2sum; do
            printf "$x " && $x android-build-tools.tar.gz | cut -d " " -f 1
          done
      - name: upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: android-build-tools.tar.gz

  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "archlinux:base"
            pkgs: "gcc"
            env: "CC=gcc CXX=g++"
          - os: "archlinux:base"
            pkgs: "clang"
            env: "CC=clang CXX=clang++"
    container:
      image: ${{ matrix.os }}
    steps:
    - name: prep archlinux
      if: startsWith(matrix.os, 'archlinux')
      run: |
        pacman -Syu --needed --noconfirm \
          ${{ matrix.pkgs }} bison cmake expat flex fmt git gtest \
          libpng ninja pkgconf protobuf
    - name: Checkout
      uses: actions/checkout@v7
      with:
        submodules: true
    - name: Prepare
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
    - name: Build
      run: |
        test -n "${{ matrix.env }}" && export ${{ matrix.env }}
        cmake -B build -G Ninja
        cmake --build build
    - name: Check
      run: |
        ./build/vendor/aapt version
        ./build/vendor/aapt2 version

  mingw:
    runs-on: windows-latest
    strategy:
      matrix:
        msystem: [clang64, ucrt64]
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Install dependencies
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        install: base-devel git
        pacboy: cc cmake expat fmt gtest libpng ninja pkgconf protobuf
    - name: Prepare
      run: |
        git submodule update --init --depth 1
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        cd vendor/core
        git config core.symlinks true
        MSYS='winsymlinks:nativestrict' git restore --source=HEAD :/ || true
    - name: Build
      run: |
        cmake -B build -G Ninja
        cmake --build build
    - name: Check
      run: |
        ./build/vendor/aapt version
        ./build/vendor/aapt2 version
